In [4]:
import os, copy, time
from cognite.power import PowerClient

In [5]:
client = PowerClient(api_key=os.environ["POWERDUMMY_API_KEY"])

In [6]:
trafo = client.power_transformers.list()
trafo

[<cognite.power.data_classes.PowerAsset object at 0x7f253b100198>, <cognite.power.data_classes.PowerAsset object at 0x7f256dce7d68>, <cognite.power.data_classes.PowerAsset object at 0x7f256dce7e10>, <cognite.power.data_classes.PowerAsset object at 0x7f256dce7c18>, <cognite.power.data_classes.PowerAsset object at 0x7f256dce7cc0>]

In [7]:
ss = trafo[0].substation()
ss

In [8]:
ss.ac_line_segments()

In [9]:
for ls in ss.ac_line_segments():
    display(ls.connected_terminals())

In [10]:
ss.time_series()

[]