In [9]:
import os, copy, time
from cognite.power import PowerClient
#client = PowerClient(project="dev1",api_key=os.environ["STATNETT_PROD_API_KEY"],
#                    base_url='https://statnett.cognitedata.com')

In [10]:
client = PowerClient(api_key=os.environ["POWERDUMMY_API_KEY"])

In [11]:
trafo = client.transformers.list()
trafo

[<cognite.power.data_classes.PowerAsset object at 0x7fd066245320>, <cognite.power.data_classes.PowerAsset object at 0x7fd066245c50>, <cognite.power.data_classes.PowerAsset object at 0x7fd066245c88>, <cognite.power.data_classes.PowerAsset object at 0x7fd030c9ed30>, <cognite.power.data_classes.PowerAsset object at 0x7fd030c9ee10>]

In [12]:
ss = trafo[0].substation()
ss

In [13]:
ss.line_segments()

In [14]:
for ls in ss.line_segments():
    display(ls.connected_terminals())

In [15]:
ss.time_series()

[]